### PR TITLE
Update release to 0.6.3

### PR DESCRIPTION
**Pull request by olivier-stasse**
This release is suppose to fix the two problems specified previously in the comment:
https://github.com/jbeder/yaml-cpp/pull/538
https://github.com/jbeder/yaml-cpp/pull/597

Tested (and needed) on macOS Catalina.

Proposed to fix https://github.com/ros2/yaml_cpp_vendor/issues/19

### CODE REVIEW

**Comment by clalancette** [comment]
Thanks for the change.  I'm going to run full CI on it on all platforms, just to be sure that there are no surprises here:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13278/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8210/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11012/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13312/)
* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/13312/)
* CentOS [Build Status](http://ci.ros2.org/job/ci_linux-centos/93/)

**Comment by clalancette** [comment]
@olivier-stasse Hm, sorry to say, but Linux is very unhappy with this change.  Can you take a look?  Thanks.

**Comment by clalancette** [comment]
Note that I redirected this PR from `foxy` -> `master`.  Our usual development workflow is to first get things into master, then think about backporting them to supported distributions.

@olivier-stasse also, the DCO bot is unhappy.  Can you rebase and sign-off all of the commits here?

**Comment by olivier-stasse** [comment]
Dear @clalancette,
I rebased my PR on master and corrected the DCO.
The package is compiling on ros2_foxy on ubuntu 20.04 LTS.
The problem was that the library was compiled in static mode only.

I have a problem with rviz_common but I do think this is not related...

**Comment by clalancette** [comment]
Excellent, thanks for all of that.  Here is CI on the change again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13291/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8222/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11025/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13331/)

**Comment by clalancette** [comment]
Unfortunately, it looks like macOS is not happy with this change.  It is failing to run many tests, all of them with a dyld error on yaml-cpp symbols.  @olivier-stasse can you take a look?

**Comment by olivier-stasse** [comment]
Dear @clalancette,
Sorry for the failure, do you have a way to reproduce the problem ? Is there a docker ?

Because I do not have the same on my own mac.

A detailed report follows.
Best Olivier.

On my side I did:
```
colcon build --symlink --packages-above yaml_cpp_vendor 
```
to check if the system was breaking at the compiling step and found nothing.
Then I did:
```
colcon test --symlink --packages-above yaml_cpp_vendor 
```
and got:
```
Starting >>> yaml_cpp_vendor
Finished <<< yaml_cpp_vendor [0.11s]           
Starting >>> rosbag2_storage
Starting >>> rviz_common
Finished <<< rosbag2_storage [11.0s]                                               
Starting >>> rosbag2_cpp
Starting >>> rosbag2_storage_default_plugins
Finished <<< rosbag2_storage_default_plugins [12.8s]                                                                     
Finished <<< rosbag2_cpp [17.5s]                                               
Starting >>> rosbag2_compression
Starting >>> rosbag2_converter_default_plugins
Finished <<< rviz_common [39.2s]                                                                                                   
Starting >>> rviz_visual_testing_framework
Finished <<< rosbag2_converter_default_plugins [13.2s]                                                                                              
Finished <<< rosbag2_compression [18.4s]                                                                
Starting >>> rosbag2_transport
Finished <<< rviz_visual_testing_framework [12.2s]                                                    
Starting >>> rviz_default_plugins
[Processing: rosbag2_transport, rviz_default_plugins]                                              
[Processing: rosbag2_transport, rviz_default_plugins]                                                  
[Processing: rosbag2_transport, rviz_default_plugins]                                                        
--- stderr: rviz_default_plugins                                                                             
Errors while running CTest
---
Finished <<< rviz_default_plugins [1min 47s]	[ with test failures ]
Starting >>> rviz2
Finished <<< rviz2 [11.0s]                                                              
[Processing: rosbag2_transport]                               
--- stderr: rosbag2_transport                                 
Errors while running CTest
---
Finished <<< rosbag2_transport [2min 35s]	[ with test failures ]
Starting >>> ros2bag
Finished <<< ros2bag [9.57s]                  
Starting >>> rosbag2_tests
[Processing: rosbag2_tests]                          
Finished <<< rosbag2_tests [37.5s]                   
Starting >>> rosbag2
Finished <<< rosbag2 [3.01s]                  

Summary: 14 packages finished [4min 13s]
  2 packages had stderr output: rosbag2_transport rviz_default_plugins
  2 packages had test failures: rosbag2_transport rviz_default_plugins
```
```rosbag2_transport``` has only one timeout error.
```rviz_default_plugins```has errors when testing a motion of the mouse
None of them seems to be related to the log of Jenkins which shows the following error:
```
dyld: Symbol not found: __ZN4YAML6detail9node_data12empty_scalarE
```
on ```rosbag2_storage/test_storage_factory```
I checked the link of the dynamic library on my macOS using ```otool -L``` but it is linked against the right library:
```
otool -L ./build/rosbag2_storage/test_storage_factory 
./build/rosbag2_storage/test_storage_factory:
	@rpath/librosbag2_storage.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libament_index_cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libclass_loader.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/console_bridge/lib/libconsole_bridge.1.0.dylib (compatibility version 1.0.0, current version 0.0.0)
	/usr/local/opt/tinyxml2/lib/libtinyxml2.8.dylib (compatibility version 8.0.0, current version 8.0.0)
	@rpath/librcpputils.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcutils.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libyaml-cpp.0.6.dylib (compatibility version 0.6.0, current version 0.6.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
```

**Comment by clalancette** [comment]
> Sorry for the failure, do you have a way to reproduce the problem ? Is there a docker ?

No, unfortunately macOS doesn't support Docker.  One significant difference is that our CI runs on Mojave, and I believe you are on Catalina.  Other than testing on a Mojave machine, I don't exactly know how else to reproduce.

**Comment by clalancette** [comment]
I'm going to close this one in favor of #23 (where we are still going to have to figure out the problems with macOS).

**Pull request closed without merging**
