### PR TITLE
build shared lib only if BUILD_SHARED_LIBS is set

### PR DESCRIPTION
**Pull request by hannes09**
with this change yaml_cpp_vendor also build as a static lib if BUILD_SHARED_LIBS=OFF

### CODE REVIEW

**Comment by methylDragon** [comment]
Hi there! With the merge of https://github.com/ament/ament_cmake/pull/390 , we can now merge this, with one change.

Could you help to add this line here, please? Once you do I'll launch CI and work towards getting this merged!

find_package(ament_cmake REQUIRED)
find_package(rcpputils REQUIRED)
find_package(rcutils REQUIRED)
find_package(rmw REQUIRED)
find_package(rosidl_default_generators REQUIRED)

ament_add_default_options() <<<--- THIS ONE! ⭐
ament_export_dependencies(ament_cmake_core)
ament_export_dependencies(rcpputils)
ament_export_dependencies(rcutils)
ament_export_dependencies(rmw)

**Review by methylDragon — CHANGES_REQUESTED** [review]
See above post

**Comment by hannes09** [comment]
I have added `ament_add_default_options`, but now the build fails.

**Comment by methylDragon** [comment]
@ros-pull-request-builder retest this please

**Review by methylDragon — APPROVED** [review]

**Comment by methylDragon** [comment]
I forgot ci ..

my bad

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16955/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11519/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17353/)

**Pull request merged**
