### PR TITLE
Removed warnigns

### PR DESCRIPTION
**Pull request by ahcorde**
There are som warnings when compiling with clang https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/1868/clang-tidy/new/folder.-1318783583/

The PR should fix them

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
Rather than doing this change, I think we should just patch the CMakeLists.txt to remove the `-Wshadow` flag: https://github.com/jbeder/yaml-cpp/blob/f7320141120f720aecc4c32be25586e7da9eb978/CMakeLists.txt#L107

My main reason for doing it that way is so that the patch is smaller and easier to fix on future upgrades.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20951/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15250/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21625/)

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20952/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15251/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21626/)

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
